sensor:
- platform: sql
  db_url: !secret mariaDB_url
  queries:
    - name: DB size
      query: 'SELECT table_schema "homeassistant", Round(Sum(data_length + index_length) / 1073741824, 1) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
      column: 'value'
      unit_of_measurement: GB