sensor:
- platform: solaredge
  api_key: !secret se_api
  site_id: !secret se_site 
  name: SolarEdge    
- platform: pvoutput
  system_id: 61105
  api_key: !secret Solar_API
  scan_interval: 150
- platform: template
  sensors:
    # power_consumption:
    #   value_template: '{% if is_state_attr("sensor.pvoutput", "power_consumption", "NaN") %}0{% else %}{{ states.sensor.pvoutput.attributes.power_consumption }}{% endif %}'
    #   friendly_name: 'Using'
    #   unit_of_measurement: 'Watt'
    # energy_consumption:
    #   value_template: '{{ "%0.1f"|format(states.sensor.pvoutput.attributes.energy_consumption|float/1000) }}'
    #   friendly_name: 'Used'
    #   unit_of_measurement: 'kWh'
    power_generation:
      value_template: '{% if is_state_attr("sensor.pvoutput", "power_generation", "NaN") %}0{% else %}{{ states.sensor.pvoutput.attributes.power_generation }}{% endif %}'
      friendly_name: 'Generating'
      unit_of_measurement: 'Watts'
    energy_generation:
      value_template: '{% if is_state_attr("sensor.pvoutput", "energy_generation", "NaN") %}0{% else %}{{ "%0.2f"|format(states.sensor.pvoutput.attributes.energy_generation|float/1000) }}{% endif %}'
      friendly_name: 'Generated'
      unit_of_measurement: 'kWh'
- platform: template
  sensors:
    grid_power_production:
      value_template: "{{ states('sensor.power_generation') | float - states('sensor.power_monitor_total_watts') | float }}"
      unit_of_measurement: 'Watts'
      friendly_name: 'Grid Production'
