##############################################################################
# Automations and required components to display information messages on HASP

input_text:
  hasp_entryway_messagetext:
    name: entryway Message Text
    icon: mdi:playlist-edit
    max: 126
  hasp_entryway_messageqr:
    name: entryway Message QR
    icon: mdi:qrcode-edit
    max: 47

input_number:
  hasp_entryway_messagetime:
    name: entryway Message Time
    icon: mdi:clock-end
    mode: box
    min: 1
    max: 600
    step: 1

group:
  entryway_messagedisplay:
    name: entryway Message Display
    entities:
      - input_text.hasp_entryway_messagetext
      - input_text.hasp_entryway_messageqr
      - input_number.hasp_entryway_messagetime
      - automation.hasp_entryway_00_messagedisplaytext
      - automation.hasp_entryway_00_messagedisplayqr
      - automation.hasp_entryway_00_messagedisplaytextqr

automation:
##############################################################################
# Display text message only
  - alias: hasp_entryway_00_messagedisplaytext
    trigger: []
    action:
    - service: mqtt.publish
      data_template:
        topic: 'hasp/entryway/command/p[0].b[1].txt'
        payload: '"{{ states.input_text.hasp_entryway_messagetext.state }}"'
    - service: mqtt.publish
      data:
        topic: 'hasp/entryway/command/page'
        payload: '0'
    - service: mqtt.publish
      data:
        topic: 'hasp/entryway/command'
        payload: 'vis 3,0'
    - service: mqtt.publish
      data:
        topic: 'hasp/entryway/command'
        payload: 'vis 1,1'
    - delay: '00:00:{{ states.input_number.hasp_entryway_messagetime.state | int }}'
    - service: mqtt.publish
      data_template:
        topic: 'hasp/entryway/command/page'
        payload: '{{ states.input_number.hasp_entryway_activepage.state | int }}'

##############################################################################
# Display qr message only
  - alias: hasp_entryway_00_messagedisplayqr
    trigger: []
    action:
    - service: mqtt.publish
      data_template:
        topic: 'hasp/entryway/command/p[0].b[3].txt'
        payload: '"{{ states.input_text.hasp_entryway_messageqr.state }}"'
    - service: mqtt.publish
      data:
        topic: 'hasp/entryway/command/page'
        payload: '0'
    - service: mqtt.publish
      data:
        topic: 'hasp/entryway/command'
        payload: 'vis 1,0'
    - service: mqtt.publish
      data:
        topic: 'hasp/entryway/command'
        payload: 'vis 3,1'
    - delay: '00:00:{{ states.input_number.hasp_entryway_messagetime.state | int }}'
    - service: mqtt.publish
      data:
        topic: 'hasp/entryway/command'
        payload: 'vis 3,0'
    - service: mqtt.publish
      data:
        topic: 'hasp/entryway/command'
        payload: 'vis 1,1'
    - service: mqtt.publish
      data_template:
        topic: 'hasp/entryway/command/page'
        payload: '{{ states.input_number.hasp_entryway_activepage.state | int }}'

##############################################################################
# Display text and qr message
  - alias: hasp_entryway_00_messagedisplaytextqr
    trigger: []
    action:
    - service: mqtt.publish
      data_template:
        topic: 'hasp/entryway/command/p[0].b[1].txt'
        payload: '"{{ states.input_text.hasp_entryway_messagetext.state }}"'
    - service: mqtt.publish
      data_template:
        topic: 'hasp/entryway/command/p[0].b[3].txt'
        payload: '"{{ states.input_text.hasp_entryway_messageqr.state }}"'
    - service: mqtt.publish
      data:
        topic: 'hasp/entryway/command/page'
        payload: '0'
    - service: mqtt.publish
      data:
        topic: 'hasp/entryway/command'
        payload: 'vis 1,1'
    - service: mqtt.publish
      data:
        topic: 'hasp/entryway/command'
        payload: 'vis 3,1'
    - delay: '00:00:{{ states.input_number.hasp_entryway_messagetime.state | int }}'
    - service: mqtt.publish
      data:
        topic: 'hasp/entryway/command'
        payload: 'vis 3,0'
    - service: mqtt.publish
      data_template:
        topic: 'hasp/entryway/command/page'
        payload: '{{ states.input_number.hasp_entryway_activepage.state | int }}'