esphome:
  name: mudroom
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
  - ssid: DrZzs-NoT
    password: !secret NoT
  - ssid: ADEN
    password: Holiness
  # manual_ip:
  #   static_ip: 192.168.1.19
  #   gateway: 192.168.1.1
  #   subnet: 255.255.255.0
  # ap:
  #   ssid: mudroom
  #   password: "12345678"
web_server:
  port: 80
# captive_portal: 

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

switch:
- platform: gpio
  name: "Mudroom Fan"
  pin: GPIO5
  id: relay_2
- platform: gpio
  name: "Mudroom Light"
  pin: GPIO4
  id: relay_1

binary_sensor:
- platform: gpio
  pin:
    number: GPIO12
    mode: INPUT_PULLUP
    inverted: True
  name: "Mudroom Light Button"
  on_press:
    - switch.toggle: relay_1
- platform: gpio
  pin:
    number: GPIO13
    mode: INPUT_PULLUP
    inverted: True
  name: "Mudroom Fan Button"
  on_press:
    - switch.toggle: relay_2
    
- platform: gpio
  pin: GPIO02 #D4
  name: "Mudroom Motion"
  device_class: motion
  on_press:
    then:
      - switch.turn_on: relay_1
      - delay: 300s
      - switch.turn_off: relay_1

sensor:
  - platform: wifi_signal
    name: "Mudroom WiFi Strength"
    update_interval: 300s

  - platform: uptime
    name: Mudroom Uptime
    